# Generated by Django 6.0.6 on 2026-06-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('description', models.TextField()),
                ('technology_used', models.CharField(max_length=200)),
                ('github_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
