# Generated by Django 6.0.6 on 2026-06-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=150)),
                ('experience_type', models.CharField(choices=[('academic', 'Academic'), ('professional', 'Professional')], max_length=20)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
